# Data Preprocessing

## Download & export data tables

### Download Microsoft OHLCV with `yfinance` library

**Search for the ticker code**

YFinance: https://finance.yahoo.com/

- [ ] Microsoft: ???

In [11]:
import yfinance as yf
import plotly.graph_objects as go
df_msft = yf.download(tickers= "MSFT", period = '10y', multi_level_index=False, auto_adjust=False)

[*********************100%***********************]  1 of 1 completed

### Download any ticker

- [x] Microsoft: MSFT
- [ ] Bitcoin: ???

In [2]:
ticker = 'BTC'
df_BTC = yf.download(ticker, multi_level_index=False, auto_adjust=False)
df_BTC

[*********************100%***********************]  1 of 1 completed

            Adj Close      Close       High        Low       Open   Volume
Date
2025-11-28  40.169998  40.169998  41.220001  39.965000  41.180000  1517900
2025-12-01  37.849998  37.849998  38.375000  37.105999  38.200001  2447200
2025-12-02  40.310001  40.310001  40.875000  39.139999  39.259998  2609700
2025-12-03  41.150002  41.150002  41.474998  40.639999  41.000000  1617200
2025-12-04  40.970001  40.970001  41.290001  40.240002  41.090000  1243300
2025-12-05  39.549999  39.549999  40.509998  39.029999  40.060001  2078800
2025-12-08  40.200001  40.200001  40.625000  39.660000  40.439999  1980600
2025-12-09  41.230000  41.230000  41.900002  39.849998  39.990002  3023400
2025-12-10  40.959999  40.959999  41.849998  40.540001  40.730000  2664800
2025-12-11  40.650002  40.650002  40.650002  39.520000  39.930000  3868900
2025-12-12  39.950001  39.950001  41.040001  39.605000  40.790001  2756400
2025-12-15  37.970001  37.970001  39.790001  37.669998  39.580002  3637200
2025-12-16  38.770000  38.770000  38.994999  38.415001  38.459999  4889100
2025-12-17  37.980000  37.980000  39.980000  37.740002  38.830002  5353500
2025-12-18  37.450001  37.450001  39.529999  37.349998  39.180000  3601600
2025-12-19  38.970001  38.970001  39.549999  38.410000  38.939999  2405100
2025-12-22  39.080002  39.080002  40.009998  38.880001  39.794998  2811000
2025-12-23  38.790001  38.790001  39.070000  38.290001  38.759998  2494700
2025-12-24  38.610001  38.610001  38.770000  38.220001  38.560001  1329500
2025-12-26  38.740002  38.740002  39.389999  38.310001  39.369999  2429100

## Visualize the data with plotly

https://plotly.com/python/candlestick-charts/

In [3]:
df_msft

Price            Close        High         Low        Open    Volume
Ticker            MSFT        MSFT        MSFT        MSFT      MSFT
Date
2025-11-28  492.010010  492.630005  486.649994  487.600006  14386700
2025-12-01  486.739990  489.859985  484.649994  488.440002  23964000
2025-12-02  490.000000  493.500000  486.320007  486.720001  19562700
2025-12-03  477.730011  484.239990  475.200012  476.320007  34615100
2025-12-04  480.839996  481.320007  476.489990  479.760010  22318200
2025-12-05  483.160004  483.399994  478.880005  482.519989  22608700
2025-12-08  491.019989  492.299988  484.380005  484.890015  21965900
2025-12-09  492.019989  492.119995  488.500000  489.100006  14696100
2025-12-10  478.559998  484.250000  475.079987  484.029999  35756200
2025-12-11  483.470001  486.029999  475.859985  476.630005  24669200
2025-12-12  478.529999  482.450012  476.339996  479.820007  21248100
2025-12-15  474.820007  480.720001  472.519989  480.100006  23727700
2025-12-16  476.390015  477.890015  470.880005  471.910004  20705600
2025-12-17  476.119995  480.000000  475.000000  476.910004  24527200
2025-12-18  483.980011  489.600006  477.890015  478.190002  28573500
2025-12-19  485.920013  487.850006  482.489990  487.359985  70836100
2025-12-22  484.920013  488.730011  482.690002  486.119995  16963000
2025-12-23  486.850006  487.829987  484.739990  484.980011  14683600
2025-12-24  488.019989  489.160004  484.829987  485.679993   5855900
2025-12-26  487.709991  488.119995  485.959991  486.709991   8822100

In [12]:

df_msft = yf.download(tickers="MSFT", period = '10y',multi_level_index=False, auto_adjust=False)
df = df_msft

go.Figure(data=[go.Candlestick(x=df.index,
                open=df['Open'],
                high=df['High'],
                low=df['Low'],
                close=df['Close'])])

[*********************100%***********************]  1 of 1 completed

In [5]:
df = df_BTC

go.Figure(data=[go.Candlestick(
    x=df.index,
    open=df['Open'],
    high=df['High'],
    low=df['Low'],
    close=df['Close'])])

## Export the data

### Microsoft data

#### Drop `Adj Close`

- To not confuse the `Close` and `Adj Close`

In [13]:
df_msft = df_msft.drop(columns='Adj Close')

#### To Excel

- Create a folder called `data`

In [14]:
 df_msft.to_excel('data/microsoft_stck_price.xlsx')

#### To CSV

- Less size in memory

In [17]:
df_msft.to_csv('data/microsoft_stock_price.csv')

### Bitcoin data altogether (step by step)

#### Define ticker

In [ ]:
ticker = 'BTC-USD'
ticker

'BTC-USD'

#### Download OLHVC

In [ ]:
df_ticker = yf.download(ticker, multi_level_index=False, auto_adjust=False)
df_ticker

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2014-09-17,465.864014,468.174011,452.421997,457.334015,457.334015,21056800
2014-09-18,456.859985,456.859985,413.104004,424.440002,424.440002,34483200
...,...,...,...,...,...,...
2023-05-29,28075.591797,28432.039062,27563.876953,27745.884766,27745.884766,15181308984
2023-05-30,27751.460938,27884.162109,27637.660156,27862.630859,27862.630859,12420773888

#### Create file path

In [ ]:
file_path = f'data/{ticker}.xlsx'
file_path

'data/BTC-USD.xlsx'

#### Export to Excel

In [ ]:
df_ticker.to_excel(file_path)

#### Export to CSV

In [ ]:
df_ticker.to_csv(f'data/{ticker}.csv')

#### Snippet

In [ ]:
ticker = 'TSLA'
df_ticker = yf.download(ticker, multi_level_index=False, auto_adjust=False)
df_ticker.to_excel(f'data/{ticker}.xlsx')
df_ticker.to_csv(f'data/{ticker}.csv')

[*********************100%***********************]  1 of 1 completed

## [ ] Data Preprocessing

In [ ]:
???

,Open,High,Low,Close,Volume,change_tomorrow,change_tomorrow_direction
Date,,,,,,,
2016-12-08,56.325228,56.582507,55.902560,56.058762,21220800,-1.549143,DOWN
2016-12-09,56.214968,56.959234,56.169027,56.940857,27349400,-0.321692,DOWN
...,...,...,...,...,...,...,...
2023-03-14,256.750000,261.070007,255.860001,260.790009,33620300,-1.751806,DOWN
2023-03-15,259.980011,266.480011,259.209991,265.440002,46028000,-3.895731,DOWN

### Load the data

In [ ]:
import pandas as pd

df_microsoft = pd.read_excel(
    'data/Microsoft_Stock_Price_Historical_Daily.xlsx',
    parse_dates=['Date'], index_col=0
)

df_microsoft

### Filter the data

![](src/Microsoft_x_LinkedIn.png)

## Create new columns

### Tomorrow's percentage change

### Did the stock go up or down?

## Export preprocessed DataFrame into an Excel